[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/",

    # Windows likes its abbreviations.
    "crates/gpui_windows/src/directx_renderer.rs",
    "crates/gpui_windows/src/events.rs",
    "crates/gpui_windows/src/direct_write.rs",
    "crates/gpui_windows/src/window.rs",
    
    # Macos apis
    "crates/gpui_macos/src/dispatcher.rs",
]

[default]
extend-ignore-re = [
    # macOS version
    "Big Sur",
    # Stripped version of reserved keyword `type`
    "typ",
]
check-filename = true
